remote_theme: pages-themes/primer@v0.6.0

plugins:
- jekyll-remote-theme
- jekyll-toc
- jekyll-mermaid

use_math: true
toc: true
mermaid: true

markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax
  input: GFM
  auto_ids: true
